// Generated by open-dynamic-workflows. Keep this tiny wrapper in your project.
export { default } from "file:///D:/Open_dynamicworkflows/open-dynamic-workflows/packages/opencode-plugin/src/index.js";
export * from "file:///D:/Open_dynamicworkflows/open-dynamic-workflows/packages/opencode-plugin/src/index.js";
