#!/usr/bin/env node
/**
 * odw-daemon — CLI for the open-dynamic-workflows local daemon.
 *
 *   start [--foreground] [--port N] [--host H]
 *   stop
 *   status
 *   restart [--resume]
 *   logs [--follow] [--lines N]
 *   run --prompt "<text>" | --script <file> [--cwd <dir>] [--wait]
 *   integrate <agent>
 *   doctor [agent]
 *   db-check
 */

import { readFileSync, existsSync, statSync, openSync, readSync, closeSync, watchFile, unwatchFile, mkdtempSync, rmSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { Command } from 'commander';
import { DEFAULT_PORT, loadConfig, ensureHome } from './config.js';
import { daemonPaths, spawnDetached, daemonStatusFromPidFile, stopDaemon, writePidFile, installShutdownHandlers } from './process.js';

const program = new Command();
program
  .name('odw-daemon')
  .description('Local orchestration daemon for open-dynamic-workflows')
  .version('open-dynamic-workflows · rolling release', '-v, --version', 'print version info');

const color = {
  ok: (s) => `\x1b[32m${s}\x1b[0m`,
  warn: (s) => `\x1b[33m${s}\x1b[0m`,
  err: (s) => `\x1b[31m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  head: (s) => `\x1b[38;5;105m${s}\x1b[0m`,
};

function formatDuration(totalSeconds) {
  const s = Math.max(0, Math.floor(Number(totalSeconds) || 0));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s % 60}s`;
  return `${s}s`;
}

/** Resolve the daemon token lazily per call (env wins over the file), so a
 *  token generated by a daemon that just started is picked up without restart. */
function daemonToken() {
  if (process.env.ODW_DAEMON_TOKEN) return process.env.ODW_DAEMON_TOKEN;
  try {
    // BOM-strip + trim — same precedent as config.json parsing in config.js.
    const raw = readFileSync(ensureHome().tokenPath, 'utf8');
    return (raw.charCodeAt(0) === 0xfeff ? raw.slice(1) : raw).trim() || null;
  } catch {
    return null; // absent/unreadable file = no token
  }
}

/** Daemon-API fetch with the bearer header attached to EVERY request. A 401
 *  means the daemon IS running but the token is missing/wrong — print that
 *  guidance and exit non-zero; never report "daemon offline". */
async function apiFetch(port, path, init = {}) {
  const token = daemonToken();
  const headers = { ...(init.headers ?? {}) };
  if (token) headers.authorization = `Bearer ${token}`;
  const res = await fetch(`http://127.0.0.1:${port}${path}`, { ...init, headers });
  if (res.status === 401) {
    console.error(`${color.err('✗')} daemon is running but rejected the request (401): auth token missing or wrong`);
    console.error(`  ${color.warn('fix:')} copy the token from ~/.odw/daemon.token, or set ODW_DAEMON_TOKEN, then retry`);
    process.exit(1);
  }
  return res;
}

async function healthcheck(port) {
  try {
    const res = await apiFetch(port, '/health', { signal: AbortSignal.timeout(2000) });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

program
  .command('start')
  .description('start the daemon (background by default)')
  .option('--foreground', 'run in the foreground (containers, debugging)')
  .option('--port <port>', 'port to listen on')
  .option('--host <host>', 'host to bind (default 127.0.0.1)')
  .action(async (opts) => {
    const config = loadConfig();
    const port = Number(opts.port ?? config.daemon.port ?? DEFAULT_PORT);

    const existing = await healthcheck(port);
    if (existing) {
      console.log(`${color.ok('✓')} daemon already running on port ${port}`);
      return;
    }

    if (opts.foreground) {
      const { startDaemon } = await import('./index.js');
      const daemon = await startDaemon({ port, host: opts.host });
      writePidFile();
      installShutdownHandlers({ server: daemon.server, store: daemon.store, logger: daemon.logger });
      await daemon.resumability.resumeAll();
      console.log(`${color.ok('✓')} daemon running on ${opts.host ?? '127.0.0.1'}:${daemon.port} (foreground)`);
      return; // keeps running until signalled
    }

    const pid = spawnDetached(opts.port ? ['--port', String(port)] : []);
    // wait for the child to come up (≤15s)
    for (let i = 0; i < 30; i++) {
      await new Promise((r) => setTimeout(r, 500));
      if (await healthcheck(port)) {
        const { logFile } = daemonPaths();
        console.log(`${color.ok('✓')} daemon started on 127.0.0.1:${port}`);
        console.log(`  pid  ${pid}`);
        console.log(`  log  ${logFile}`);
        return;
      }
    }
    console.error(`${color.err('✗')} daemon did not become healthy within 15s — check logs: ${daemonPaths().logFile}`);
    process.exitCode = 1;
  });

program
  .command('stop')
  .description('stop the daemon')
  .action(async () => {
    const signalled = stopDaemon();
    if (!signalled) {
      console.log(`${color.warn('⚠')} daemon was not running`);
      return;
    }
    for (let i = 0; i < 20; i++) {
      await new Promise((r) => setTimeout(r, 250));
      if (!daemonStatusFromPidFile().running) {
        console.log(`${color.ok('✓')} daemon stopped`);
        return;
      }
    }
    console.error(`${color.err('✗')} daemon did not exit within 5s`);
    process.exitCode = 1;
  });

program
  .command('status')
  .description('daemon health and active workflows')
  .option('--port <port>', 'port to probe')
  .action(async (opts) => {
    const config = loadConfig();
    const port = Number(opts.port ?? config.daemon.port ?? DEFAULT_PORT);
    const pidStatus = daemonStatusFromPidFile();
    const health = await healthcheck(port);
    if (!health) {
      console.log(`${color.err('●')} status   not running${pidStatus.pid ? color.dim(` (stale pid ${pidStatus.pid})`) : ''}`);
      process.exitCode = 1;
      return;
    }
    const lines = [
      ['status', color.ok('running')],
      ['port', String(port)],
      ['pid', String(pidStatus.pid ?? 'unknown')],
      ['uptime', formatDuration(health.uptime)],
      ['active workflows', String(health.activeWorkflows)],
      ['active agents', `${health.activeAgents}/${health.maxConcurrency}`],
      ['queued agents', String(health.queuedAgents)],
    ];
    console.log(color.head('odw daemon'));
    for (const [k, v] of lines) console.log(`  ${k.padEnd(18)} ${v}`);
  });

program
  .command('restart')
  .description('stop, start, and optionally resume interrupted workflows')
  .option('--resume', 'resume interrupted workflows after restart')
  .option('--port <port>')
  .action(async (opts) => {
    stopDaemon();
    for (let i = 0; i < 20 && daemonStatusFromPidFile().running; i++) {
      await new Promise((r) => setTimeout(r, 250));
    }
    const config = loadConfig();
    const port = Number(opts.port ?? config.daemon.port ?? DEFAULT_PORT);
    spawnDetached(['--port', String(port)]);
    for (let i = 0; i < 30; i++) {
      await new Promise((r) => setTimeout(r, 500));
      if (await healthcheck(port)) break;
    }
    // foreground start already resumes; the flag is honored for parity/docs
    console.log(`${color.ok('✓')} daemon restarted${opts.resume ? ' (interrupted workflows resume automatically)' : ''}`);
  });

program
  .command('logs')
  .description('show daemon logs')
  .option('--follow', 'stream new lines')
  .option('--lines <n>', 'number of trailing lines', '50')
  .action(async (opts) => {
    const { logFile } = daemonPaths();
    if (!existsSync(logFile)) {
      console.log(color.dim('(no log file yet)'));
      return;
    }
    const tail = (n) => {
      const content = readFileSync(logFile, 'utf8').trimEnd().split('\n');
      return content.slice(-n).join('\n');
    };
    console.log(tail(Number(opts.lines)));
    if (opts.follow) {
      let position = statSync(logFile).size;
      watchFile(logFile, { interval: 500 }, () => {
        const size = statSync(logFile).size;
        if (size <= position) return;
        const fd = openSync(logFile, 'r');
        const buffer = Buffer.alloc(size - position);
        readSync(fd, buffer, 0, buffer.length, position);
        closeSync(fd);
        position = size;
        process.stdout.write(buffer.toString('utf8'));
      });
      process.on('SIGINT', () => {
        unwatchFile(logFile);
        process.exit(0);
      });
      await new Promise(() => {}); // follow until interrupted
    }
  });

program
  .command('run')
  .description('plan + execute a workflow from the shell')
  .option('--prompt <text>', 'natural-language workflow prompt')
  .option('--script <file>', 'run a saved orchestration script directly')
  .option('--cwd <dir>', 'working directory for workflow tools', process.cwd())
  .option('--port <port>')
  .option('--no-wait', 'do not wait for completion')
  .action(async (opts) => {
    if (!opts.prompt && !opts.script) {
      console.error(`${color.err('✗')} provide --prompt "<text>" or --script <file>`);
      process.exitCode = 1;
      return;
    }
    const config = loadConfig();
    const port = Number(opts.port ?? config.daemon.port ?? DEFAULT_PORT);
    if (!(await healthcheck(port))) {
      console.error(`${color.err('✗')} daemon is not running — start it with: odw-daemon start`);
      process.exitCode = 1;
      return;
    }

    // Fail fast with guidance if the configured model can't be reached — BEFORE
    // we spend time planning and rendering a plan the user can't actually run.
    try {
      const check = await (await apiFetch(port, '/config/check', { signal: AbortSignal.timeout(5000) })).json();
      if (check && check.ok === false) {
        // `reason` already names the offending model (e.g. "default
        // claude-sonnet-4-6: …"), so don't prefix a redundant — and, since the
        // readiness payload carries no top-level model id, "undefined" — model
        // label of our own.
        console.error(`${color.err('✗')} configured model is not usable: ${check.reason}`);
        console.error(`  ${color.warn('fix:')} edit ~/.odw/config.json — add an API key under "apiKeys", or set "models.default" to a local model like "ollama:llama3" (no key needed).`);
        process.exitCode = 1;
        return;
      }
    } catch {
      /* preflight is best-effort; continue if the endpoint is unavailable */
    }

    let plan;
    if (opts.script) {
      const script = readFileSync(resolve(opts.script), 'utf8');
      plan = { script, prompt: `script:${opts.script}`, topology: 'hybrid', estimate: { totalAgents: 0 } };
    } else {
      const planRes = await apiFetch(port, '/workflows/plan', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ prompt: opts.prompt }),
      });
      if (!planRes.ok) {
        console.error(`${color.err('✗')} planning failed: ${(await planRes.text()).slice(0, 300)}`);
        process.exitCode = 1;
        return;
      }
      ({ plan } = await planRes.json());
      const e = plan.estimate;
      console.log(color.head('plan'));
      console.log(`  topology     ${plan.topology}`);
      console.log(`  agents       ~${e.totalAgents} (max ${e.maxConcurrent} concurrent)`);
      console.log(`  tokens       ~${e.tokens.toLocaleString()}`);
      console.log(`  est. cost    $${e.costUSD}`);
      console.log(`  est. time    ~${e.minutes} min`);
      console.log(`  verification ${plan.hasVerification ? color.ok('yes (adversarial)') : color.dim('no — add "verify"/"audit"/"review" intent for a verification pass')}`);
    }

    const execRes = await apiFetch(port, '/workflows/exec', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ plan, cwd: resolve(opts.cwd) }),
    });
    if (!execRes.ok) {
      console.error(`${color.err('✗')} exec failed: ${(await execRes.text()).slice(0, 300)}`);
      process.exitCode = 1;
      return;
    }
    const { workflowId } = await execRes.json();
    console.log(`${color.ok('▶')} workflow ${workflowId} running`);

    if (opts.wait === false) return;

    // Poll the record with short, resilient requests (a single long-held
    // connection is fragile over multi-minute runs). Show live progress, then
    // the final result or a clear failure reason — never make the user open a log.
    const TERMINAL = new Set(['completed', 'failed', 'cancelled']);
    let record;
    let lastLine = '';
    for (;;) {
      try {
        const r = await apiFetch(port, `/workflows/${workflowId}`, { signal: AbortSignal.timeout(8000) });
        record = await r.json();
      } catch {
        await new Promise((res) => setTimeout(res, 2000));
        continue;
      }
      const line = `  ${record.completed_agents ?? 0} done / ${record.failed_agents ?? 0} failed`;
      if (line !== lastLine) {
        process.stdout.write(`\r${color.dim(line)}        `);
        lastLine = line;
      }
      if (TERMINAL.has(record.status)) break;
      await new Promise((res) => setTimeout(res, 2000));
    }
    process.stdout.write('\n');

    if (record.status === 'completed') {
      const res = await apiFetch(port, `/workflows/${workflowId}/result`);
      const body = await res.json();
      console.log(`${color.ok('✓')} completed`);
      console.log(JSON.stringify(body.result, null, 2));
    } else {
      console.error(`${color.err('✗')} workflow ${record.status}`);
      if (record.error) console.error(`  ${color.err('reason:')} ${record.error}`);
      else console.error(color.dim(`  (no reason recorded — see logs: odw-daemon logs)`));
      process.exitCode = 1;
    }
  });

program
  .command('integrate')
  .description('install ODW into an agentic coder (MCP, skill, or native plugin)')
  .argument('<agent>', 'mcp|codex|codex-plugin|cursor|kimi|gemini|zed|zcode|opencode|vscode|antigravity|openclaw|all')
  .option('--target <dir>', 'project directory for project-local configs', process.cwd())
  .option('--home <dir>', 'home directory for user-level configs', homedir())
  .option('--repo <dir>', 'open-dynamic-workflows checkout to point adapters at')
  .option('--json', 'print machine-readable JSON')
  .action(async (agent, opts) => {
    const { installAgentIntegration } = await import('./integrations.js');
    const result = installAgentIntegration(agent, {
      targetDir: resolve(opts.target),
      home: resolve(opts.home),
      ...(opts.repo ? { repoRoot: resolve(opts.repo) } : {}),
    });
    if (opts.json) {
      printJson({ ok: true, agent, result });
      return;
    }
    console.log(`${color.ok('ok')} installed ${agent} integration`);
    for (const line of integrationLines(result)) console.log(`  ${line}`);
    console.log('');
    console.log('next:');
    console.log('  odw-daemon start');
    console.log('  then ask your agent: workflow: audit this repo for real bugs');
  });

program
  .command('doctor')
  .description('check daemon readiness and installed agent integration files')
  .argument('[agent]', 'mcp|codex|codex-plugin|cursor|kimi|gemini|zed|zcode|opencode|vscode|antigravity|openclaw|all', 'all')
  .option('--target <dir>', 'project directory for project-local configs', process.cwd())
  .option('--home <dir>', 'home directory for user-level configs', homedir())
  .option('--repo <dir>', 'open-dynamic-workflows checkout integrations should point at')
  .option('--port <port>', 'daemon port to probe')
  .option('--json', 'print machine-readable JSON')
  .action(async (agent, opts) => {
    const { doctorAgentIntegration } = await import('./integrations.js');
    const report = doctorAgentIntegration(agent, {
      targetDir: resolve(opts.target),
      home: resolve(opts.home),
      ...(opts.repo ? { repoRoot: resolve(opts.repo) } : {}),
    });

    const config = loadConfig();
    const port = Number(opts.port ?? config.daemon.port ?? DEFAULT_PORT);
    const health = await healthcheck(port);
    const daemon = health
      ? { ok: true, port, ...health }
      : { ok: false, port };
    const ok = report.ok && daemon.ok;

    if (opts.json) {
      printJson({ ok, agent, integration: report, daemon });
      if (!ok) process.exitCode = 1;
      return;
    }

    console.log(`${report.ok ? color.ok('[ok]') : color.err('[x]')} ${agent} integration ${report.ok ? 'ready' : 'needs attention'}`);
    for (const group of report.groups) {
      // In `all` mode a never-installed adapter is neutral — collapse it to one
      // "skipped" line instead of a wall of red "missing" checks. An explicit
      // single-adapter request still lists every check so the user sees details.
      if (agent === 'all' && group.status === 'absent') {
        console.log(`  ${color.dim('[-]')} ${group.agent.padEnd(30)} ${color.dim('not installed — skipped')}`);
        continue;
      }
      for (const item of group.checks) {
        console.log(`  ${item.ok ? color.ok('[ok]') : color.err('[x]')} ${item.label.padEnd(30)} ${item.message}`);
        console.log(`       ${color.dim(item.path)}`);
      }
    }

    if (health) {
      console.log(`${color.ok('[ok]')} daemon running on 127.0.0.1:${port}`);
    } else {
      console.log(`${color.warn('[!]')} daemon not running on 127.0.0.1:${port}`);
      console.log('      start it with: odw-daemon start');
    }

    if (!report.ok || !health) process.exitCode = 1;
  });

program
  .command('db-check')
  .description('migration dry-run against a temporary database')
  .action(async () => {
    const dir = mkdtempSync(join(tmpdir(), 'odw-dbcheck-'));
    try {
      const { openDatabase } = await import('./db.js');
      const db = openDatabase(join(dir, 'check.db'));
      const version = db.pragma('user_version', { simple: true });
      const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map((r) => r.name);
      db.close();
      console.log(`${color.ok('✓')} migrations applied cleanly (user_version=${version})`);
      console.log(`  tables: ${tables.join(', ')}`);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

ensureHome();
program.parseAsync(process.argv).catch((error) => {
  console.error(`${color.err('✗')} ${error.message}`);
  process.exit(1);
});

function integrationLines(result) {
  if (!result) return [];
  if (Array.isArray(result.steps)) return result.steps.flatMap(integrationLines);
  return Object.entries(result)
    .filter(([key]) => key !== 'kind' && key !== 'server')
    .map(([key, value]) => `${String(key).padEnd(12)} ${value}`);
}

function printJson(value) {
  console.log(JSON.stringify(value, null, 2));
}
