const PROJECTS = [
  ['open-clinic-triage-assistant', 'Healthcare', 'Open Clinic Triage Assistant', 'Intake symptoms, risk factors, and urgency signals, then produce safe triage guidance with escalation rules.'],
  ['rural-telehealth-workflow-kit', 'Healthcare', 'Rural Telehealth Workflow Kit', 'Coordinate low-bandwidth patient scheduling, visit notes, prescription follow-up, and referral tracking.'],
  ['medication-interaction-checker', 'Healthcare', 'Medication Interaction Checker', 'Check common medication interaction risks and produce patient-safe warning workflows.'],
  ['hospital-bed-capacity-dashboard', 'Healthcare', 'Hospital Bed Capacity Dashboard', 'Aggregate admissions, discharge estimates, staffing limits, and bed availability.'],
  ['clinical-trial-matcher', 'Healthcare', 'Clinical Trial Matcher', 'Match patient eligibility criteria against public clinical trial data.'],
  ['mental-health-resource-navigator', 'Healthcare', 'Mental Health Resource Navigator', 'Route users to crisis, therapy, peer-support, and local services based on need and geography.'],
  ['public-health-outbreak-tracker', 'Healthcare', 'Public Health Outbreak Tracker', 'Collect, normalize, and summarize outbreak reports from public sources.'],
  ['medical-claims-denial-analyzer', 'Healthcare', 'Medical Claims Denial Analyzer', 'Explain denial reasons, missing documents, and appeal steps.'],
  ['nursing-shift-load-balancer', 'Healthcare', 'Nursing Shift Load Balancer', 'Optimize nurse assignments based on acuity, certifications, and fairness.'],
  ['open-dental-care-planner', 'Healthcare', 'Open Dental Care Planner', 'Generate treatment-plan explanations, cost ranges, and follow-up schedules.'],
  ['disaster-relief-resource-coordinator', 'Emergency', 'Disaster Relief Resource Coordinator', 'Match shelters, supplies, volunteers, and urgent requests during emergencies.'],
  ['flood-risk-community-mapper', 'Emergency', 'Flood Risk Community Mapper', 'Combine elevation, rainfall, drainage, and historical flood data into local risk reports.'],
  ['wildfire-evacuation-planner', 'Emergency', 'Wildfire Evacuation Planner', 'Generate evacuation checklists, route risks, animal support, and vulnerable-population plans.'],
  ['emergency-radio-message-summarizer', 'Emergency', 'Emergency Radio Message Summarizer', 'Turn radio and dispatch logs into structured incident updates.'],
  ['humanitarian-aid-inventory-tracker', 'Emergency', 'Humanitarian Aid Inventory Tracker', 'Track donated goods, expiration dates, demand, distribution, and shortages.'],
  ['refugee-services-navigator', 'Emergency', 'Refugee Services Navigator', 'Map legal aid, housing, healthcare, language services, and job support.'],
  ['missing-persons-coordination-board', 'Emergency', 'Missing Persons Coordination Board', 'Structure reports, leads, search areas, and family communications.'],
  ['community-cooling-center-planner', 'Emergency', 'Community Cooling Center Planner', 'Identify heat-risk areas and plan accessible cooling-center coverage.'],
  ['crisis-volunteer-credentialing-tool', 'Emergency', 'Crisis Volunteer Credentialing Tool', 'Verify skills, availability, location, and safety training.'],
  ['emergency-translation-request-router', 'Emergency', 'Emergency Translation Request Router', 'Match language needs with verified interpreters during incidents.'],
  ['small-farm-crop-planner', 'Agriculture', 'Small Farm Crop Planner', 'Recommend planting schedules, irrigation needs, pest risks, and market timing.'],
  ['soil-health-recommendation-engine', 'Agriculture', 'Soil Health Recommendation Engine', 'Analyze soil reports and produce regenerative agriculture action plans.'],
  ['food-waste-redistribution-network', 'Agriculture', 'Food Waste Redistribution Network', 'Match surplus food from restaurants and grocers to shelters and food banks.'],
  ['local-food-supply-chain-mapper', 'Agriculture', 'Local Food Supply Chain Mapper', 'Track producers, distributors, storage, and delivery bottlenecks.'],
  ['open-pest-surveillance-system', 'Agriculture', 'Open Pest Surveillance System', 'Collect pest reports, identify hotspots, and suggest mitigation.'],
  ['farmer-grant-application-assistant', 'Agriculture', 'Farmer Grant Application Assistant', 'Convert farm details into grant eligibility and application checklists.'],
  ['community-garden-operating-system', 'Agriculture', 'Community Garden Operating System', 'Manage plots, volunteers, harvest logs, and shared resources.'],
  ['irrigation-leak-detection-workflow', 'Agriculture', 'Irrigation Leak Detection Workflow', 'Analyze water usage anomalies and maintenance priorities.'],
  ['livestock-health-log-analyzer', 'Agriculture', 'Livestock Health Log Analyzer', 'Detect disease-risk patterns from feeding, behavior, and treatment logs.'],
  ['farm-equipment-maintenance-planner', 'Agriculture', 'Farm Equipment Maintenance Planner', 'Schedule service based on hours, season, parts, and downtime risk.'],
  ['open-building-energy-auditor', 'Energy', 'Open Building Energy Auditor', 'Analyze bills, appliance data, insulation, and weather to recommend savings.'],
  ['solar-feasibility-estimator', 'Energy', 'Solar Feasibility Estimator', 'Estimate rooftop solar potential using location, roof profile, shading, and incentives.'],
  ['community-microgrid-planner', 'Energy', 'Community Microgrid Planner', 'Design resilient local energy-sharing scenarios for outages.'],
  ['ev-charger-placement-optimizer', 'Energy', 'EV Charger Placement Optimizer', 'Recommend charger locations based on traffic, equity, grid access, and demand.'],
  ['utility-bill-explainer', 'Energy', 'Utility Bill Explainer', 'Decode charges, rate plans, anomalies, and savings opportunities.'],
  ['carbon-accounting-toolkit-for-smes', 'Energy', 'Carbon Accounting Toolkit for SMEs', 'Estimate Scope 1, 2, and 3 emissions from invoices and operations.'],
  ['open-heat-pump-retrofit-planner', 'Energy', 'Open Heat Pump Retrofit Planner', 'Evaluate building readiness, costs, rebates, and contractor tasks.'],
  ['grid-outage-root-cause-reporter', 'Energy', 'Grid Outage Root Cause Reporter', 'Structure outage reports, equipment failures, weather causes, and restoration ETAs.'],
  ['energy-poverty-risk-mapper', 'Energy', 'Energy Poverty Risk Mapper', 'Identify communities at risk from high bills, poor insulation, and extreme weather.'],
  ['battery-storage-sizing-assistant', 'Energy', 'Battery Storage Sizing Assistant', 'Recommend battery capacity for homes, clinics, schools, or microbusinesses.'],
  ['tenant-rights-navigator', 'Housing', 'Tenant Rights Navigator', 'Explain lease clauses, local protections, repair rights, and escalation steps.'],
  ['affordable-housing-eligibility-matcher', 'Housing', 'Affordable Housing Eligibility Matcher', 'Match households with housing programs and required documents.'],
  ['homeless-services-intake-router', 'Housing', 'Homeless Services Intake Router', 'Route people to shelter, food, medical, legal, and case-management services.'],
  ['building-code-compliance-reviewer', 'Housing', 'Building Code Compliance Reviewer', 'Review plans against public code checklists and flag missing evidence.'],
  ['rental-repair-case-tracker', 'Housing', 'Rental Repair Case Tracker', 'Track complaints, landlord responses, deadlines, photos, and agency filings.'],
  ['neighborhood-zoning-explainer', 'Housing', 'Neighborhood Zoning Explainer', 'Translate zoning rules into plain-language development possibilities.'],
  ['housing-market-displacement-monitor', 'Housing', 'Housing Market Displacement Monitor', 'Track rent spikes, evictions, permits, and demographic shifts.'],
  ['open-home-accessibility-audit', 'Housing', 'Open Home Accessibility Audit', 'Assess homes for mobility, vision, hearing, and aging-in-place needs.'],
  ['vacant-property-reuse-planner', 'Housing', 'Vacant Property Reuse Planner', 'Evaluate vacant lots and buildings for housing, gardens, clinics, or community use.'],
  ['fair-housing-complaint-assistant', 'Housing', 'Fair Housing Complaint Assistant', 'Structure discrimination reports and evidence timelines.'],
  ['worker-safety-incident-analyzer', 'Labor', 'Worker Safety Incident Analyzer', 'Categorize incidents, root causes, preventive controls, and OSHA-style logs.'],
  ['job-training-pathway-recommender', 'Labor', 'Job Training Pathway Recommender', 'Match skills, goals, local demand, and training programs.'],
  ['wage-theft-evidence-organizer', 'Labor', 'Wage Theft Evidence Organizer', 'Structure hours, pay stubs, contracts, messages, and claim timelines.'],
  ['union-contract-explainer', 'Labor', 'Union Contract Explainer', 'Translate collective bargaining agreements into searchable plain-language guidance.'],
  ['small-business-compliance-calendar', 'Labor', 'Small Business Compliance Calendar', 'Track tax, license, insurance, payroll, and filing deadlines.'],
  ['open-hiring-bias-auditor', 'Labor', 'Open Hiring Bias Auditor', 'Review job descriptions and hiring rubrics for exclusionary patterns.'],
  ['apprenticeship-matcher', 'Labor', 'Apprenticeship Matcher', 'Match candidates with trade programs, prerequisites, locations, and deadlines.'],
  ['workplace-accommodation-planner', 'Labor', 'Workplace Accommodation Planner', 'Suggest reasonable accommodation workflows and documentation.'],
  ['freelancer-contract-risk-reviewer', 'Labor', 'Freelancer Contract Risk Reviewer', 'Flag payment, IP, termination, liability, and scope risks.'],
  ['local-labor-market-dashboard', 'Labor', 'Local Labor Market Dashboard', 'Aggregate job postings, wages, skills, and training gaps.'],
  ['school-attendance-early-warning-system', 'Education', 'School Attendance Early Warning System', 'Identify chronic absenteeism risks and intervention options.'],
  ['open-iep-support-organizer', 'Education', 'Open IEP Support Organizer', 'Help families organize goals, services, evaluations, and meeting notes.'],
  ['teacher-lesson-differentiation-assistant', 'Education', 'Teacher Lesson Differentiation Assistant', 'Adapt lessons for reading levels, disabilities, and multilingual learners.'],
  ['scholarship-matcher', 'Education', 'Scholarship Matcher', 'Match students to scholarships based on profile, deadlines, essays, and eligibility.'],
  ['community-college-transfer-planner', 'Education', 'Community College Transfer Planner', 'Map credits, requirements, deadlines, and transfer risks.'],
  ['open-curriculum-gap-analyzer', 'Education', 'Open Curriculum Gap Analyzer', 'Compare curriculum against standards and identify missing topics.'],
  ['after-school-program-scheduler', 'Education', 'After-School Program Scheduler', 'Optimize rooms, instructors, students, transportation, and safety coverage.'],
  ['school-meal-access-planner', 'Education', 'School Meal Access Planner', 'Identify eligibility, applications, delivery, and summer meal options.'],
  ['adult-literacy-program-toolkit', 'Education', 'Adult Literacy Program Toolkit', 'Assess learner needs and build individualized reading and writing plans.'],
  ['open-career-portfolio-builder', 'Education', 'Open Career Portfolio Builder', 'Help learners turn projects, work, and volunteering into career portfolios.'],
  ['municipal-permit-navigator', 'Civic', 'Municipal Permit Navigator', 'Guide residents through permits, fees, documents, and agency steps.'],
  ['public-records-request-assistant', 'Civic', 'Public Records Request Assistant', 'Draft public-records requests and track deadlines and responses.'],
  ['city-budget-explainer', 'Civic', 'City Budget Explainer', 'Convert budget documents into plain-language summaries and issue maps.'],
  ['participatory-budgeting-platform', 'Civic', 'Participatory Budgeting Platform', 'Collect proposals, estimate costs, validate eligibility, and support voting.'],
  ['civic-issue-triage-board', 'Civic', 'Civic Issue Triage Board', 'Route potholes, lights, trash, safety, and code complaints to correct departments.'],
  ['open-procurement-watchdog', 'Civic', 'Open Procurement Watchdog', 'Analyze contracts, vendors, bids, conflicts, and spending trends.'],
  ['public-meeting-summarizer', 'Civic', 'Public Meeting Summarizer', 'Turn agendas, transcripts, and minutes into decisions, votes, and action items.'],
  ['grant-compliance-tracker-for-nonprofits', 'Civic', 'Grant Compliance Tracker for Nonprofits', 'Track deliverables, spend, reports, receipts, and deadlines.'],
  ['local-policy-impact-analyzer', 'Civic', 'Local Policy Impact Analyzer', 'Compare proposed policies against affected populations and tradeoffs.'],
  ['open-election-information-guide', 'Civic', 'Open Election Information Guide', 'Explain registration, polling places, ballot measures, and deadlines.'],
  ['cybersecurity-baseline-auditor-for-small-orgs', 'Cybersecurity', 'Cybersecurity Baseline Auditor for Small Orgs', 'Check MFA, backups, patching, access control, and incident readiness.'],
  ['open-source-dependency-risk-scanner', 'Cybersecurity', 'Open Source Dependency Risk Scanner', 'Prioritize CVEs, license issues, maintainer risk, and upgrade paths.'],
  ['phishing-simulation-planner', 'Cybersecurity', 'Phishing Simulation Planner', 'Generate ethical training campaigns, templates, and reporting workflows.'],
  ['incident-response-runbook-generator', 'Cybersecurity', 'Incident Response Runbook Generator', 'Build response plans for ransomware, data leaks, account compromise, and outages.'],
  ['privacy-policy-diff-analyzer', 'Cybersecurity', 'Privacy Policy Diff Analyzer', 'Compare privacy policies and highlight meaningful changes.'],
  ['data-retention-policy-builder', 'Cybersecurity', 'Data Retention Policy Builder', 'Map data types, retention rules, deletion workflows, and legal holds.'],
  ['access-review-automation-kit', 'Cybersecurity', 'Access Review Automation Kit', 'Review users, roles, stale accounts, privilege creep, and approvals.'],
  ['open-vendor-security-questionnaire-reviewer', 'Cybersecurity', 'Open Vendor Security Questionnaire Reviewer', 'Analyze SOC2, policies, architecture, and gaps.'],
  ['secure-configuration-checklist-generator', 'Cybersecurity', 'Secure Configuration Checklist Generator', 'Produce hardening guides for common stacks and cloud services.'],
  ['breach-notification-decision-assistant', 'Cybersecurity', 'Breach Notification Decision Assistant', 'Structure facts, jurisdictions, timelines, and notification duties.'],
  ['supply-chain-disruption-simulator', 'Supply Chain', 'Supply Chain Disruption Simulator', 'Model supplier failures, shipping delays, substitutes, and cost impact.'],
  ['open-inventory-forecasting-tool', 'Supply Chain', 'Open Inventory Forecasting Tool', 'Predict stockouts, overstock, reorder points, and seasonal demand.'],
  ['ethical-supplier-risk-mapper', 'Supply Chain', 'Ethical Supplier Risk Mapper', 'Track labor, sanctions, environmental, and geopolitical risks.'],
  ['warehouse-picking-optimizer', 'Supply Chain', 'Warehouse Picking Optimizer', 'Improve pick paths, batching, slotting, and labor allocation.'],
  ['fleet-maintenance-scheduler', 'Supply Chain', 'Fleet Maintenance Scheduler', 'Plan vehicle service based on mileage, routes, inspections, and failures.'],
  ['cold-chain-monitoring-workflow', 'Supply Chain', 'Cold Chain Monitoring Workflow', 'Track temperature excursions, spoilage risk, and corrective action.'],
  ['reverse-logistics-planner', 'Supply Chain', 'Reverse Logistics Planner', 'Manage returns, repairs, recycling, refurbishment, and resale.'],
  ['open-customs-documentation-assistant', 'Supply Chain', 'Open Customs Documentation Assistant', 'Generate customs checklists from product, country, and shipping data.'],
  ['construction-material-delay-tracker', 'Supply Chain', 'Construction Material Delay Tracker', 'Predict project delays from supplier, permit, labor, and weather data.'],
  ['circular-economy-marketplace-planner', 'Supply Chain', 'Circular Economy Marketplace Planner', 'Match waste streams, reusable materials, buyers, and compliance needs.'],
];

export function projectCatalog() {
  return PROJECTS.map(([slug, industry, title, problem], index) => ({
    id: String(index + 1).padStart(3, '0'),
    slug,
    industry,
    title,
    problem,
    license: 'Apache-2.0',
    deliverables: ['README.md', 'PRD.md', 'ARCHITECTURE.md', 'API.md', 'DATA_MODEL.md', 'SECURITY.md', 'TEST_PLAN.md', 'ROADMAP.md', 'package.json', 'src/index.js', 'test/index.test.js'],
  }));
}
